-- 진단테스트용 문제들을 추가 (미국 MAP 테스트 기준, 높은 난이도)
-- Reading, Writing, Speaking, Math 문제들을 각 학년별로 추가

-- Grade 1 문제들 (초1/Year 2)
INSERT INTO questions (question_text, question_type, subject, grade_level, system_type, options, correct_answer, explanation, difficulty_level, points) VALUES
('Look at this sentence: "The cat runs fast." Which word tells us HOW the cat runs?', 'multiple_choice', 'reading', 'Grade 1', 'us', '["cat", "runs", "fast", "the"]', 'fast', 'The word "fast" describes how the cat runs. It is an adverb.', 2, 1),
('Read this short story and write 2-3 sentences about what happens: "Sam found a lost puppy in the park. The puppy was hungry and scared. Sam gave the puppy some food and took it home to his family."', 'essay', 'reading', 'Grade 1', 'us', '[]', '', 'Student should identify main events: Sam found a puppy, puppy was hungry/scared, Sam helped and took it home.', 2, 2),
('Count and add: 🍎🍎🍎 + 🍎🍎 = ?', 'multiple_choice', 'math', 'Grade 1', 'us', '["3", "4", "5", "6"]', '5', '3 apples plus 2 apples equals 5 apples total.', 1, 1),
('Tell me about your favorite toy. Speak for 30 seconds and describe what it looks like and why you like it.', 'speaking', 'speaking', 'Grade 1', 'us', '[]', '', 'Evaluate clarity, descriptive words, and enthusiasm. Age-appropriate vocabulary expected.', 2, 2),
('Write one sentence about what you did yesterday. Use correct spelling and punctuation.', 'essay', 'writing', 'Grade 1', 'us', '[]', '', 'Check for basic sentence structure, capital letter, period, and reasonable spelling attempts.', 2, 2),

-- Grade 2 문제들 (초2/Year 3)  
('Read this passage: "Birds build nests in many different ways. Some birds use twigs and leaves. Other birds use mud and grass. Each type of bird has its own special way of making a home." What is the main idea?', 'multiple_choice', 'reading', 'Grade 2', 'us', '["Birds eat different foods", "Birds build nests in different ways", "Birds live in trees", "Birds can fly"]', 'Birds build nests in different ways', 'The passage is about how different birds build their nests differently.', 2, 2),
('After reading the bird passage, write a paragraph explaining two different ways birds build nests. Use details from the passage.', 'essay', 'reading', 'Grade 2', 'us', '[]', '', 'Student should mention twigs/leaves and mud/grass, showing comprehension of passage details.', 3, 3),
('If you have 15 stickers and give away 8 stickers to friends, how many stickers do you have left?', 'short_answer', 'math', 'Grade 2', 'us', '[]', '7', 'Subtraction: 15 - 8 = 7 stickers remaining.', 2, 2),

-- Grade 3 문제들 (초3/Year 4)
('Read this paragraph: "Maria loves to read mystery books. She enjoys trying to solve the puzzle before the main character does. Last week, she read three mystery books and solved two of the mysteries correctly." Based on this passage, what can you infer about Maria?', 'multiple_choice', 'reading', 'Grade 3', 'us', '["She dislikes reading", "She is good at solving puzzles", "She only reads one book per week", "She never solves mysteries"]', 'She is good at solving puzzles', 'The passage shows Maria enjoys mystery puzzles and successfully solved 2 out of 3, indicating skill.', 3, 2),
('Write a short story (4-5 sentences) about a child who finds something magical. Include a beginning, middle, and end.', 'essay', 'reading', 'Grade 3', 'us', '[]', '', 'Evaluate story structure, creativity, sentence variety, and narrative flow.', 3, 4),
('A bakery sells cupcakes for $2 each. If someone buys 6 cupcakes, how much money do they spend? Show your work.', 'short_answer', 'math', 'Grade 3', 'us', '[]', '$12 (6 × $2 = $12)', 'Multiplication word problem: 6 cupcakes × $2 each = $12 total.', 3, 2),

-- Grade 4 문제들 (초4/Year 5) 
('Read this passage: "The Amazon rainforest is home to millions of species of plants and animals. Scientists estimate that many species living there have not yet been discovered. The rainforest produces about 20% of the world''s oxygen and absorbs carbon dioxide from the atmosphere." What evidence supports that the Amazon is important to Earth?', 'essay', 'reading', 'Grade 4', 'us', '[]', '', 'Students should identify: produces 20% oxygen, absorbs CO2, supports biodiversity. Look for text evidence.', 4, 4),
('Which word is a synonym for "enormous"?', 'multiple_choice', 'reading', 'Grade 4', 'us', '["tiny", "huge", "medium", "colorful"]', 'huge', 'Enormous and huge both mean very large in size.', 3, 1),
('A rectangular playground is 45 feet long and 30 feet wide. What is the area of the playground in square feet?', 'short_answer', 'math', 'Grade 4', 'us', '[]', '1,350 square feet', 'Area = length × width = 45 × 30 = 1,350 square feet.', 3, 2),

-- Grade 5 문제들 (초5/Year 6)
('Read this excerpt: "The young inventor tinkered with gears and springs, determined to create something that had never been built before. After months of failed attempts and countless revisions, she finally achieved her breakthrough." Analyze the character''s traits based on this passage. Write a paragraph with specific evidence.', 'essay', 'reading', 'Grade 5', 'us', '[]', '', 'Look for traits like persistent, creative, determined. Students should quote text evidence like "months of failed attempts" and "countless revisions."', 4, 5),
('In the sentence "The storm approached menacingly," what part of speech is "menacingly"?', 'multiple_choice', 'reading', 'Grade 5', 'us', '["noun", "verb", "adjective", "adverb"]', 'adverb', 'Menacingly describes HOW the storm approached, making it an adverb.', 4, 2),
('Convert this improper fraction to a mixed number: 17/5', 'short_answer', 'math', 'Grade 5', 'us', '[]', '3 2/5', 'Divide: 17 ÷ 5 = 3 remainder 2, so 3 2/5.', 4, 2),

-- Grade 6 문제들 (초6/Year 7)
('Read the passage: "The ancient civilization of Mesopotamia, often called the cradle of civilization, developed between the Tigris and Euphrates rivers around 3500 BCE. This region saw the rise of the first cities, the invention of writing, and the establishment of complex governmental systems." What does "cradle of civilization" most likely mean in this context?', 'multiple_choice', 'reading', 'Grade 6', 'us', '["The place where babies were born", "The birthplace or origin of civilization", "A place where people sleep", "The end of civilization"]', 'The birthplace or origin of civilization', 'A cradle is where babies begin life, so "cradle of civilization" means where civilization began.', 3, 2),
('Based on the Mesopotamia passage, write an analytical paragraph explaining why this region was so important to human development. Use at least three pieces of evidence from the text.', 'essay', 'reading', 'Grade 6', 'us', '[]', '', 'Students should analyze using evidence: first cities, invention of writing, complex governments, geographic advantages of river location.', 4, 5),
('Sarah is planning a rectangular garden. The length is 3 times the width. If the perimeter is 48 feet, what are the dimensions of the garden?', 'short_answer', 'math', 'Grade 6', 'us', '[]', 'Width: 6 feet, Length: 18 feet', 'Set up equation: 2(w + 3w) = 48, solve for w = 6, then length = 18.', 4, 3),

-- Grade 7 문제들 (중1/Year 8)
('Analyze the theme in this excerpt: "Marcus stared at the acceptance letter, knowing that attending the prestigious academy meant leaving behind everything familiar. His dreams of success warred with his fear of the unknown." Write a paragraph analyzing the internal conflict and its broader meaning.', 'essay', 'reading', 'Grade 7', 'us', '[]', '', 'Look for analysis of internal conflict, theme of growth vs. comfort, use of literary terms, and connection to universal human experience.', 5, 6),
('What is the solution to this equation: 3x + 7 = 22?', 'short_answer', 'math', 'Grade 7', 'us', '[]', 'x = 5', 'Subtract 7 from both sides: 3x = 15, then divide by 3: x = 5.', 4, 2),

-- Grade 8 문제들 (중2/Year 9)  
('Read this passage from a historical text: "The Industrial Revolution fundamentally transformed not only how goods were produced, but also how people lived, worked, and related to one another. Traditional rural communities gave way to urban centers, fundamentally altering the social fabric of society." Compare and contrast traditional rural life with industrial urban life based on this passage and your background knowledge. Write a well-developed essay.', 'essay', 'reading', 'Grade 8', 'us', '[]', '', 'Evaluate historical analysis, comparison/contrast structure, use of text evidence, and connections to broader historical knowledge.', 5, 8),
('Solve for y: 2y - 3(y + 4) = 15', 'short_answer', 'math', 'Grade 8', 'us', '[]', 'y = -27', 'Distribute: 2y - 3y - 12 = 15, combine: -y - 12 = 15, solve: y = -27.', 5, 3),

-- Grade 9 문제들 (중3/Year 10)
('Analyze the use of symbolism in this excerpt: "The lighthouse stood sentinel against the storm, its beam cutting through the darkness like hope piercing despair." Write an analytical essay examining how the author uses the lighthouse as a symbol and its effect on the passage''s meaning.', 'essay', 'reading', 'Grade 9', 'us', '[]', '', 'Students should analyze lighthouse as symbol of guidance/hope, discuss literary techniques, and evaluate effectiveness of symbolism.', 5, 8),
('Factor completely: x² - 9x + 14', 'short_answer', 'math', 'Grade 9', 'us', '[]', '(x - 2)(x - 7)', 'Find two numbers that multiply to 14 and add to -9: -2 and -7.', 4, 3),

-- Grade 10 문제들 (고1/Year 11)
('Read this excerpt from a contemporary novel: "The protagonist''s journey through the abandoned city served as both a literal quest for survival and a metaphorical exploration of identity in a post-apocalyptic world where traditional social structures had collapsed." Analyze how the author uses the setting to develop themes about identity and society. Write a comprehensive literary analysis.', 'essay', 'reading', 'Grade 10', 'us', '[]', '', 'Evaluate understanding of symbolism, theme development, literary analysis skills, and ability to connect setting to deeper meanings.', 5, 10),
('Solve the quadratic equation: 2x² + 5x - 3 = 0', 'short_answer', 'math', 'Grade 10', 'us', '[]', 'x = 1/2 or x = -3', 'Use quadratic formula or factor: (2x - 1)(x + 3) = 0, so x = 1/2 or x = -3.', 5, 4),

-- Grade 11 문제들 (고2/Year 12)
('Analyze this passage from "The Great Gatsby": "So we beat on, boats against the current, borne back ceaselessly into the past." Write a critical analysis examining Fitzgerald''s use of metaphor, the concept of the American Dream, and how this conclusion reflects the novel''s central themes. Support your analysis with specific textual evidence.', 'essay', 'reading', 'Grade 11', 'us', '[]', '', 'Evaluate sophisticated literary analysis, understanding of American Dream critique, metaphor analysis, and integration of textual evidence.', 5, 12),
('Find the derivative of f(x) = 3x³ - 2x² + 5x - 1', 'short_answer', 'math', 'Grade 11', 'us', '[]', 'f''(x) = 9x² - 4x + 5', 'Apply power rule: 3(3x²) - 2(2x) + 5(1) - 0 = 9x² - 4x + 5.', 5, 3),

-- Grade 12 문제들 (고3/Year 13)
('In Shakespeare''s "Hamlet," the protagonist''s soliloquy "To be or not to be" primarily explores which philosophical concept?', 'multiple_choice', 'reading', 'Grade 12', 'us', '["The nature of existence and suicide", "Political corruption in Denmark", "The ghost of his father", "His relationship with Ophelia"]', 'The nature of existence and suicide', 'This famous soliloquy contemplates whether life is worth living and considers suicide as an escape from suffering.', 5, 3),
('Write a comprehensive literary analysis comparing the treatment of power and corruption in Shakespeare''s "Hamlet" and Orwell''s "1984." Examine how each author uses literary techniques to explore these themes and their relevance to contemporary society. Your essay should be 500-700 words.', 'essay', 'reading', 'Grade 12', 'us', '[]', '', 'Evaluate comparative analysis, sophisticated understanding of themes, literary technique analysis, and contemporary connections.', 5, 15),
('Given f(x) = 2x³ - 6x² + 4x - 2, find f''(x) and determine the x-coordinates of any inflection points.', 'short_answer', 'math', 'Grade 12', 'us', '[]', 'f''(x) = 12x - 12; inflection point at x = 1', 'Take second derivative: f''(x) = 12x - 12. Set equal to 0: x = 1.', 5, 4);

-- Speaking과 Writing 문제들 추가
INSERT INTO questions (question_text, question_type, subject, grade_level, system_type, options, correct_answer, explanation, difficulty_level, points) VALUES
-- Speaking 문제들
('Tell me about your favorite holiday. Speak for 1 minute about what you do and why you enjoy it.', 'speaking', 'speaking', 'Grade 1', 'us', '[]', '', 'Evaluate clarity, vocabulary, and ability to stay on topic for young learners.', 2, 3),
('Describe a fun game you like to play with friends. Explain the rules in 90 seconds.', 'speaking', 'speaking', 'Grade 2', 'us', '[]', '', 'Assess explanation skills, sequence of ideas, and clear communication.', 2, 3),
('You have 2 minutes to persuade your classmates to read your favorite book. Include the title, main characters, and why they should read it.', 'speaking', 'speaking', 'Grade 3', 'us', '[]', '', 'Evaluate persuasive speaking, organization, and enthusiasm.', 3, 4),
('Compare two different seasons. Speak for 2 minutes about their differences and which you prefer, using comparison words.', 'speaking', 'speaking', 'Grade 4', 'us', '[]', '', 'Assess use of comparison language and organized presentation.', 3, 4),
('You have 3 minutes to explain a scientific concept you learned recently. Make it interesting for younger students.', 'speaking', 'speaking', 'Grade 5', 'us', '[]', '', 'Evaluate explanation skills, age-appropriate language, and engagement techniques.', 4, 5),
('Present an argument for or against school uniforms. You have 3 minutes to persuade your audience with logical reasons.', 'speaking', 'speaking', 'Grade 6', 'us', '[]', '', 'Assess persuasive techniques, logical reasoning, and formal presentation skills.', 4, 5),
('Describe a historical figure you admire. In 3 minutes, explain their contributions and why they inspire you.', 'speaking', 'speaking', 'Grade 7', 'us', '[]', '', 'Evaluate historical knowledge, analytical thinking, and articulate expression.', 4, 6),
('Give a 4-minute presentation on a current global issue. Include causes, effects, and potential solutions.', 'speaking', 'speaking', 'Grade 8', 'us', '[]', '', 'Assess complex analysis, organization, and mature communication skills.', 5, 7),
('Deliver a 4-minute persuasive speech on a topic you''re passionate about. Use rhetorical devices and evidence.', 'speaking', 'speaking', 'Grade 9', 'us', '[]', '', 'Evaluate advanced rhetorical skills, evidence use, and sophisticated delivery.', 5, 8),
('Present a 5-minute analysis of a piece of literature, artwork, or film. Discuss themes, techniques, and personal interpretation.', 'speaking', 'speaking', 'Grade 10', 'us', '[]', '', 'Assess critical analysis skills, cultural literacy, and articulate expression.', 5, 8),
('Deliver a 5-minute speech analyzing a philosophical or ethical dilemma. Present multiple perspectives before stating your position.', 'speaking', 'speaking', 'Grade 11', 'us', '[]', '', 'Evaluate complex reasoning, perspective-taking, and sophisticated argumentation.', 5, 10),
('Give a 6-minute presentation on a topic of your expertise, demonstrating leadership and advanced communication skills.', 'speaking', 'speaking', 'Grade 12', 'us', '[]', '', 'Assess mastery-level presentation skills, expertise demonstration, and leadership qualities.', 5, 10),

-- Writing 문제들
('Draw a picture of your family and write one sentence about each person.', 'essay', 'writing', 'Grade 1', 'us', '[]', '', 'Check basic sentence structure, family vocabulary, and creative expression.', 2, 3),
('Write a short story (4-5 sentences) about an animal adventure. Include a beginning, middle, and end.', 'essay', 'writing', 'Grade 2', 'us', '[]', '', 'Evaluate story structure, creativity, and age-appropriate language.', 2, 4),
('Write a letter to a friend describing your perfect day. Include at least 6 sentences and proper letter format.', 'essay', 'writing', 'Grade 3', 'us', '[]', '', 'Assess letter format, descriptive language, and personal voice.', 3, 4),
('Write a persuasive paragraph (5-7 sentences) arguing for a new rule at your school. Include reasons and examples.', 'essay', 'writing', 'Grade 4', 'us', '[]', '', 'Evaluate persuasive structure, supporting details, and logical reasoning.', 3, 5),
('Write a compare and contrast essay (3 paragraphs) about two different sports or hobbies.', 'essay', 'writing', 'Grade 5', 'us', '[]', '', 'Assess essay organization, comparison techniques, and paragraph development.', 4, 6),
('Write a narrative essay (4-5 paragraphs) about a time you overcame a challenge. Include dialogue and descriptive details.', 'essay', 'writing', 'Grade 6', 'us', '[]', '', 'Evaluate narrative techniques, character development, and descriptive writing.', 4, 7),
('Write an argumentative essay (5 paragraphs) on whether social media has more positive or negative effects on teenagers.', 'essay', 'writing', 'Grade 7', 'us', '[]', '', 'Assess argumentative structure, evidence use, and counterargument consideration.', 4, 8),
('Write a research-based essay (5-6 paragraphs) on an environmental issue. Include citations and a solution-focused conclusion.', 'essay', 'writing', 'Grade 8', 'us', '[]', '', 'Evaluate research integration, formal writing style, and solution-oriented thinking.', 5, 9),
('Write a literary analysis essay (5-6 paragraphs) analyzing symbolism in a novel you''ve read. Include textual evidence.', 'essay', 'writing', 'Grade 9', 'us', '[]', '', 'Assess literary analysis skills, textual evidence use, and sophisticated writing.', 5, 10),
('Write a persuasive research essay (6-7 paragraphs) on a contemporary social issue. Include multiple sources and counterarguments.', 'essay', 'writing', 'Grade 10', 'us', '[]', '', 'Evaluate advanced research skills, complex argumentation, and source integration.', 5, 12),
('Write a synthesis essay (7-8 paragraphs) combining perspectives from multiple sources on a complex topic like artificial intelligence or climate change.', 'essay', 'writing', 'Grade 11', 'us', '[]', '', 'Assess synthesis skills, critical thinking, and sophisticated academic writing.', 5, 14),
('Write a comprehensive research paper (8-10 paragraphs) on a topic of your choice, demonstrating mastery of academic writing conventions.', 'essay', 'writing', 'Grade 12', 'us', '[]', '', 'Evaluate mastery-level research, writing, and critical analysis skills.', 5, 15);