-- Enable RLS on all tables that need it
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_test_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reading_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_masters ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_section_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_test_permissions ENABLE ROW LEVEL SECURITY;