// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klotxqfcjlzdevohzqlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsb3R4cWZjamx6ZGV2b2h6cWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MjYwODksImV4cCI6MjA3MTAwMjA4OX0.XozLy3dxLDH8bEfXCQNSYP0XdPqvck1_XHIYrINGZaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});